version: "3.8"

networks:
  traefik:
    external: true

services:
  traefik:
    restart: always
    image: traefik:latest
    networks:
      - traefik
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config:/etc/traefik:ro
      - ./config/tls:/config/tls:ro
    healthcheck:
      test: traefik healthcheck --ping
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s

