http:
  routers:
    http2https:
      entryPoints:
        - http
      rule: "HostRegexp(`{any:.+}`)"
      middlewares:
        - http2https
        - hsts
      service: noop@internal

    api:
      rule: "Host(`dev.run`)"
      service: api@internal
      middlewares:
        #- auth
      tls: {}

  middlewares:
    http2https:
      redirectScheme:
        scheme: https
        permanent: true
    hsts:
      headers:
        sslRedirect: true
        forceSTSHeader: true
        STSIncludeSubdomains: true
        STSSeconds: 2628000
        STSPreload: true
        browserXSSFilter: true
        contentTypeNosniff: true
        frameDeny: true
    auth:
      basicAuth:
        removeHeader: true
        users:
          - admin:$apr1$dtw3acs1$hytP3PXN/MW2Wwef8F6OF/
