providers:
  docker:
    watch: true
    exposedByDefault: false
  file:
    watch: true
    directory: /etc/traefik
    debugLogGeneratedTemplate: false

global:
  checkNewVersion: false
  sendAnonymousUsage: false

ping: {}

log:
  level: ERROR

api:
  dashboard: true

entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"